###############################
# CI: `firewheel_repo_utilities`
###############################

stages:
  - upstream

# Trigger CI for FIREWHEEL
firewheel-ci:
  stage: upstream
  trigger: firewheel/firewheel
  only:
    - main
