---
- name: Create VM resources directory
  ansible.builtin.file:
    path: "{{ download_dir }}"
    state: directory

- name: Download Python 3.7 psutil wheel
  ansible.builtin.get_url:
    url: "https://files.pythonhosted.org/packages/13/71/c25adbd9b33a2e27edbe1fc84b3111a5ad97611885d7abcbdd8d1f2bb7ca/psutil-5.9.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
    dest: "{{ download_dir }}/psutil-5.9.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
    checksum: "sha256:3054e923204b8e9c23a55b23b6df73a8089ae1d075cb0bf711d3e9da1724ded4"

- name: Download Python 3.10 psutil wheel
  ansible.builtin.get_url:
    url: "https://files.pythonhosted.org/packages/c5/4f/0e22aaa246f96d6ac87fe5ebb9c5a693fbe8877f537a1022527c47ca43c5/psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
    dest: "{{ download_dir }}/psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
    checksum: "sha256:d06016f7f8625a1825ba3732081d77c94589dca78b7a3fc072194851e88461a4"

- name: Download inotify-tools deb package
  ansible.builtin.get_url:
    url: "http://launchpadlibrarian.net/166561163/inotify-tools_3.14-1ubuntu1_amd64.deb"
    dest: "{{ download_dir }}/inotify-tools_3.14-1ubuntu1_amd64.deb"
    checksum: "sha256:1bf516e12d9064f8ac84ede869e991d04aaa2fed6c5b5b54d63aa58396b681df"

- name: Download libinotifytools deb package
  ansible.builtin.get_url:
    url: "http://launchpadlibrarian.net/166561161/libinotifytools0_3.14-1ubuntu1_amd64.deb"
    dest: "{{ download_dir }}/libinotifytools0_3.14-1ubuntu1_amd64.deb"
    checksum: "sha256:960a3f3d791443cedea6cb70d8776c38f7149634846fdf87ad749431152a8d16"

- name: Compress inotify debs into a single package
  ansible.builtin.command:
    cmd: "tar -czvf {{ download_dir }}/inotify-tools_3.14-1.tgz -C {{ download_dir }} inotify-tools_3.14-1ubuntu1_amd64.deb libinotifytools0_3.14-1ubuntu1_amd64.deb"
  args:
    chdir: "{{ download_dir }}"

- name: Clean up individual inotify deb packages
  ansible.builtin.file:
    path: "{{ download_dir }}/inotify-tools_3.14-1ubuntu1_amd64.deb"
    state: absent

- name: Clean up individual libinotifytools deb packages
  ansible.builtin.file:
    path: "{{ download_dir }}/libinotifytools0_3.14-1ubuntu1_amd64.deb"
    state: absent
